services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ['gpu']
              count: all
    ports:
      - '11434:11434'
    volumes:
      - ./data/ollama:/root/.ollama
    networks:
      - ollama_network
    environment:
      - MODELS=llama3.2
      - NVIDIA_VISIBLE_DEVICES=all

  chat-ui:
    build: .
    container_name: chat-ui
    ports:
      - '3000:3000'
    depends_on:
      - ollama
    networks:
      - ollama_network
    environment:
      - BASE_URL=http://ollama:11434/api

volumes:
  ollama: {}

networks:
  ollama_network:
    driver: bridge
